name: Deploy to Telegram

on:
  workflow_dispatch: #manual run
  release:
    types: [published]

jobs:
  send-to-telegram:
    name: send apk to telegran
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: instalation modules
        run: yarn

      - name: make gradle executable
        run: chmod +x ./android/gradle

      - name: generate apk
        run: |
          cd android
          ./gradlew bundleRelease assembleRelease
          cd ..

      - name: send apk as message #gajalan
        run: |
          cd android/app/build/outputs/apk/release/
          curl -X POST -H 'Content-Type: multipart/oform-data' -F text='App Release!' - F chat_id=$TG_CHAT_ID $TG_BOT_TOKEN/sendMessage
          curl -X POST -H 'Content-Type: multipart/oform-data' -F document=@app-release.apk - F chat_id=$TG_CHAT_ID $TG_BOT_TOKEN/sendDocument
